package domain

import "time"

type TripEventType string

const (
	TripStartEvent          TripEventType = "trip_start"
	TripStopEvent           TripEventType = "trip_stop"
	TripLocationUpdateEvent TripEventType = "trip_location_update"
)

// TripEvent saves events generated by scooter during trip
type TripEvent struct {
	ID        string
	UserID    string
	ScooterID string
	Location  GeoLocation
	Type      TripEventType
	CreatedAt time.Time
}
